site_name: Executor Engine Docs

repo_url: https://github.com/Nanguage/executor-engine

theme:
  name: material
  logo: rocket.svg
  palette: 

    # Palette toggle for light mode
    - scheme: default
      primary: deep orange
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode


nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - API Reference:
    - api-reference/engine.md
    - api-reference/job.md
    - api-reference/condition.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details

plugins:
- search
- mkdocstrings
- autorefs
